"""
This type stub file was generated by pyright.
"""

from pandas.core.indexes.base import Index, InvalidIndexError, _ensure_index, _ensure_index_from_sequences, _get_na_value, _new_Index
from pandas.core.indexes.category import CategoricalIndex
from pandas.core.indexes.multi import MultiIndex
from pandas.core.indexes.interval import IntervalIndex
from pandas.core.indexes.numeric import Float64Index, Int64Index, NumericIndex, UInt64Index
from pandas.core.indexes.range import RangeIndex
from pandas.core.indexes.timedeltas import TimedeltaIndex
from pandas.core.indexes.period import PeriodIndex
from pandas.core.indexes.datetimes import DatetimeIndex
from pandas._libs.tslib import NaT

__all__ = ['Index', 'MultiIndex', 'NumericIndex', 'Float64Index', 'Int64Index', 'CategoricalIndex', 'IntervalIndex', 'RangeIndex', 'UInt64Index', 'InvalidIndexError', 'TimedeltaIndex', 'PeriodIndex', 'DatetimeIndex', '_new_Index', 'NaT', '_ensure_index', '_ensure_index_from_sequences', '_get_na_value', '_get_combined_index', '_get_objs_combined_axis', '_union_indexes', '_get_consensus_names', '_all_indexes_same']
def _get_objs_combined_axis(objs, intersect: bool = ..., axis=...):
    ...

def _get_combined_index(indexes, intersect: bool = ...):
    ...

def _union_indexes(indexes):
    ...

def _sanitize_and_check(indexes):
    ...

def _get_consensus_names(indexes):
    ...

def _all_indexes_same(indexes):
    ...

