"""
This type stub file was generated by pyright.
"""

def get_sys_info():
    "Returns system information as a dict"
    ...

def show_versions(as_json: bool = ...):
    ...

def main():
    ...

if __name__ == "__main__":
    ...
