"""
This type stub file was generated by pyright.
"""

import logging
from typing import Any, Optional

"""
This module provides the routine to adjust subplot layouts so that there are
no overlapping axes or axes decorations.  All axes decorations are dealt with
(labels, ticks, titles, ticklabels) and some dependent artists are also dealt
with (colorbar, suptitle, legend).

Layout is done via :meth:`~matplotlib.gridspec`, with one constraint per
gridspec, so it is possible to have overlapping axes if the gridspecs
overlap (i.e. using :meth:`~matplotlib.gridspec.GridSpecFromSubplotSpec`).
Axes placed using ``figure.subplots()`` or ``figure.add_subplots()`` will
participate in the layout.  Axes manually placed via ``figure.add_axes()``
will not.

See Tutorial: :doc:`/tutorials/intermediate/constrainedlayout_guide`

"""
_log = logging.getLogger(__name__)
def get_axall_tightbbox(ax, renderer):
    '''
    Get the tight_bbox of the axis ax, and any dependent decorations, like
    a `Legend` instance.
    '''
    ...

def in_same_column(colnum0min, colnum0max, colnumCmin, colnumCmax):
    ...

def in_same_row(rownum0min, rownum0max, rownumCmin, rownumCmax):
    ...

def do_constrained_layout(fig, renderer, h_pad, w_pad, hspace: Optional[Any] = ..., wspace: Optional[Any] = ...):
    """
    Do the constrained_layout.  Called at draw time in
     ``figure.constrained_layout()``

    Parameters
    ----------


    fig: Figure
      is the ``figure`` instance to do the layout in.

    renderer: Renderer
      the renderer to use.

     h_pad, w_pad : float
       are in figure-normalized units, and are a padding around the axes
       elements.

     hspace, wspace : float
        are in fractions of the subplot sizes.

    """
    ...

def _arange_subplotspecs(gs, hspace=..., wspace=...):
    """
    arange the subplotspec children of this gridspec, and then recursively
    do the same of any gridspec children of those gridspecs...
    """
    ...

def layoutcolorbarsingle(ax, cax, shrink, aspect, location, pad=...):
    """
    Do the layout for a colorbar, to not oeverly pollute colorbar.py

    `pad` is in fraction of the original axis size.
    """
    ...

def layoutcolorbargridspec(parents, cax, shrink, aspect, location, pad=...):
    """
    Do the layout for a colorbar, to not oeverly pollute colorbar.py

    `pad` is in fraction of the original axis size.
    """
    ...

