"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

"""Utilities for interpreting CSS from Stylers for formatting non-HTML outputs
"""
class CSSWarning(UserWarning):
    """This CSS syntax cannot currently be parsed"""
    ...


class CSSResolver(object):
    """A callable for parsing and resolving CSS to atomic properties

    """
    INITIAL_STYLE = ...
    def __call__(self, declarations_str, inherited: Optional[Any] = ...):
        """ the given declarations to atomic properties

        Parameters
        ----------
        declarations_str : str
            A list of CSS declarations
        inherited : dict, optional
            Atomic properties indicating the inherited style context in which
            declarations_str is to be resolved. ``inherited`` should already
            be resolved, i.e. valid output of this method.

        Returns
        -------
        props : dict
            Atomic CSS 2.2 properties

        Examples
        --------
        >>> resolve = CSSResolver()
        >>> inherited = {'font-family': 'serif', 'font-weight': 'bold'}
        >>> out = resolve('''
        ...               border-color: BLUE RED;
        ...               font-size: 1em;
        ...               font-size: 2em;
        ...               font-weight: normal;
        ...               font-weight: inherit;
        ...               ''', inherited)
        >>> sorted(out.items())  # doctest: +NORMALIZE_WHITESPACE
        [('border-bottom-color', 'blue'),
         ('border-left-color', 'red'),
         ('border-right-color', 'red'),
         ('border-top-color', 'blue'),
         ('font-family', 'serif'),
         ('font-size', '24pt'),
         ('font-weight', 'bold')]
        """
        ...
    
    UNIT_RATIOS = ...
    FONT_SIZE_RATIOS = ...
    MARGIN_RATIOS = ...
    BORDER_WIDTH_RATIOS = ...
    def size_to_pt(self, in_val, em_pt: Optional[Any] = ..., conversions=...):
        ...
    
    def atomize(self, declarations):
        ...
    
    SIDE_SHORTHANDS = ...
    SIDES = ...
    def _side_expander(prop_fmt):
        ...
    
    expand_border_color = ...
    expand_border_style = ...
    expand_border_width = ...
    expand_margin = ...
    expand_padding = ...
    def parse(self, declarations_str):
        """Generates (prop, value) pairs from declarations

        In a future version may generate parsed tokens from tinycss/tinycss2
        """
        ...
    


