"""
This type stub file was generated by pyright.
"""

import sys

EXCEPT_MSG = """
    Pyperclip could not find a copy/paste mechanism for your system.
    For more information, please visit https://pyperclip.readthedocs.org """
PY2 = sys.version_info[0] == 2
text_type = unicode if PY2 else str
def init_osx_clipboard():
    ...

def init_gtk_clipboard():
    ...

def init_qt_clipboard():
    ...

def init_xclip_clipboard():
    ...

def init_xsel_clipboard():
    ...

def init_klipper_clipboard():
    ...

def init_no_clipboard():
    class ClipboardUnavailable(object):
        ...
    
    

