"""
This type stub file was generated by pyright.
"""

from typing import Any, Optional

""" Factory methods to create N-D panels """
def create_nd_panel_factory(klass_name, orders, slices, slicer, aliases: Optional[Any] = ..., stat_axis=..., info_axis=..., ns: Optional[Any] = ...):
    """ manufacture a n-d class:

    .. deprecated:: 0.19.0
       The recommended way to represent these types of n-dimensional data
       are with the `xarray package <http://xarray.pydata.org/en/stable/>`__.
       Pandas provides a `.to_xarray()` method to automate this conversion.

    Parameters
    ----------
    klass_name : the klass name
    orders : the names of the axes in order (highest to lowest)
    slices : a dictionary that defines how the axes map to the slice axis
    slicer : the class representing a slice of this panel
    aliases : a dictionary defining aliases for various axes
        default = { major : major_axis, minor : minor_axis }
    stat_axis : the default statistic axis default = 2
    info_axis : the info axis

    Returns
    -------
    a class object representing this panel
    """
    ...

